In [2]:
! pip install selenium

Requirement already satisfied: selenium in c:\programdata\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.25.11)

In [18]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException

#Importing requests
import requests

# importing regex
import re

1 Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ You need to find following details: A) Rank B) Name C) Artist D) Upload date E) Views

In [19]:
#1
#importing webdriver
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe")
driver.maximize_window()  #maximizing window
time.sleep(3)
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"   #"url"
driver.get(url) #loading url
time.sleep(2)

#creating empty Boxex
rank=[]
videon=[]
uploader=[]
views=[]
uploadd=[]

for i in range(1,31):
    #Rank
    dt=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[1]".format(i))
    for d in dt:
        rank.append(d.text)
    #video name
    vi=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[2]".format(i))
    for c in vi:
        videon.append(c.text)
        videon = [x.split("[")[0] for x in videon] #cleaning data
        
    #Uploader
    l=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[3]".format(i))
    for g in l:
        uploader.append(g.text)
    #Views
    vs=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[4]".format(i))
    for h in vs:
        views.append(h.text)
   #Upload date
    up=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[5]".format(i))
    for c in up:
        uploadd.append(c.text)

time.sleep(2)
#creating dataframe
ans1=pd.DataFrame({})
ans1["Rank"]=rank
ans1["Video Name"]=videon
ans1["Uploader"]=uploader
ans1["Views (billions)"]=views 
ans1["Upload Date"]=uploadd
ans1.set_index("Rank", inplace=True)
ans1

,Video Name,Uploader,Views (billions),Upload Date
Rank,,,,
1.,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,9.58,"June 17, 2016"
2.,"""Despacito""",Luis Fonsi,7.61,"January 12, 2017"
3.,"""Johny Johny Yes Papa""",LooLoo Kids,5.85,"October 8, 2016"
4.,"""Shape of You""",Ed Sheeran,5.51,"January 30, 2017"
5.,"""See You Again""",Wiz Khalifa,5.31,"April 6, 2015"
6.,"""Bath Song""",Cocomelon – Nursery Rhymes,4.60,"May 2, 2018"
7.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,4.53,"February 27, 2018"
8.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,4.47,"January 31, 2012"
9.,"""Uptown Funk""",Mark Ronson,4.34,"November 19, 2014"
10.,"""Phonics Song with Two Words""",ChuChu TV,4.27,"March 6, 2014"
11.,"""Gangnam Style""",Psy,4.24,"July 15, 2012"
12.,"""Dame Tu Cosita""",El Chombo,3.67,"April 5, 2018"
13.,"""Sugar""",Maroon 5,3.58,"January 14, 2015"
14.,"""Sorry""",Justin Bieber,3.48,"October 22, 2015"
15.,"""Roar""",Katy Perry,3.46,"September 5, 2013"
16.,"""Counting Stars""",OneRepublic,3.43,"May 31, 2013"
17.,"""Thinking Out Loud""",Ed Sheeran,3.35,"October 7, 2014"
18.,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,3.33,"May 24, 2018"
19.,"""Faded""",Alan Walker,3.17,"December 3, 2015"
20.,"""Dark Horse""",Katy Perry,3.17,"February 20, 2014"
21.,"""Girls Like You""",Maroon 5,3.16,"May 31, 2018"
22.,"""Lean On""",Major Lazer,3.12,"March 22, 2015"
23.,"""Bailando""",Enrique Iglesias,3.12,"April 11, 2014"
24.,"""Shake It Off""",Taylor Swift,3.11,"August 18, 2014"
25.,"""Let Her Go""",Passenger,3.11,"July 25, 2012"
26.,"""Axel F""",Crazy Frog,3.08,"June 16, 2009"
27.,"""Perfect""",Ed Sheeran,3.00,"November 9, 2017"
28.,"""Mi Gente""",J Balvin,3.00,"June 29, 2017"
29.,"""Waka Waka (This Time for Africa)""",Shakira,2.98,"June 4, 2010"


2.Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/. You need to find following details: A) Match title (I.e. 1st ODI) B) Series C) Place D) Date E) Time Note: - From bcci.tv home page you have reach to the international fixture page through code

In [39]:
#2
#importing webdriver
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe")

time.sleep(2)
# Opening the bcci.tv
url = "https://www.bcci.tv/"
driver.get(url)

time.sleep(2)
#going to international fixtures page
fixtures=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    

time.sleep(2)
# scrape match details urls from xpath    
urls=[]
match_page=driver.find_elements_by_xpath("//div[@class='js-list']/a")  
for i in match_page:
    urls.append(i.get_attribute('href'))
  
    
time.sleep(1)   
# make empty lists
match=[] 
series=[]
place=[]
date=[]
Time=[]
all_text = []
venue = []


for i in urls:                 #list of urls of match description pages
    driver.get(i)
    
    time.sleep(2)
    #scarping match title
    try:                    
        match_title=driver.find_element_by_xpath("//p[@class='mc-header-info__match-description']/span")
        match.append(match_title.text)
    except NoSuchElementException:#handling no such element exception
        match.append('No details available')
    
    time.sleep(2)
    #scarping series title    
    try:
        series_title=driver.find_element_by_xpath("//h1[@class='mc-header-info__title']/strong")
        series.append(series_title.text)
    except NoSuchElementException:#handling no such element exception
        series.append("No details Available")
    
    time.sleep(2)
    #scarping date of match 
    try:
        date_title=driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']/strong")
        date.append(date_title.text)
    except NoSuchElementException:#handling no such element exception
        date.append("No details Available")      
    
    time.sleep(2)
    #scarping time of the match    
    try:
        time_title=driver.find_element_by_xpath("//div[@class='mc-header-scorebox__datetime']/span")
        Time.append(time_title.text)
    except NoSuchElementException:#handling no such element exception
        Time.append("No details Available")    
      
    time.sleep(2)
     #scarping match venue    
    try:
        place_title=driver.find_element_by_xpath("//h1[@class='mc-header-info__title']")
        venue.append(place_title.text)
    except NoSuchElementException:#handling no such element exception
        place.append("No details Available")
        
    
    
# split place from text
for i in venue:
    all_text.append(i.split())
for i in all_text:
    place.append(i[-1::]) 
    
time.sleep(2)       
#preparing the dataframe
df=pd.DataFrame({"Match":match,
                "Series":series,
                "Place":place,
                "Date":date,
                "Time":Time})
df

,Match,Series,Place,Date,Time
0,MATCH 42,India v Namibia,[Dubai],No details Available,No details Available
1,1ST T20I,India v New Zealand,[Jaipur],Wednesday 17 November,19:00 IST
2,2ND T20I,India v New Zealand,[Ranchi],Friday 19 November,19:00 IST
3,3RD T20I,India v New Zealand,[Kolkata],Sunday 21 November,19:00 IST
4,1ST TEST,India v New Zealand,[Kanpur],Thursday 25 November,09:30 IST
5,2ND TEST,India v New Zealand,[Mumbai],Friday 3 December,09:30 IST
6,1ST ODI,India v West Indies,[Ahmedabad],Sunday 6 February,13:00 IST
7,2ND ODI,India v West Indies,[Jaipur],Wednesday 9 February,13:00 IST
8,3RD ODI,India v West Indies,[Kolkata],Saturday 12 February,13:00 IST
9,1ST T20I,India v West Indies,[Cuttack],Tuesday 15 February,19:00 IST

3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details: A) Name B) Description Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [46]:
url = "https://www.guru99.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)
time.sleep(3)
exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])

df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

Legality Response number from our URL is: <Response [200]>

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...


*Q4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ You have to find following details: A) Rank B) State C) GSDP(18-19) D) GSDP(17-18) E) Share(2017) F) GDP($ billion) Note: - From statisticstimes home page you have to reach to economy page through code

In [40]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe") 
time.sleep(2)

# Opening the statisticstimes.com
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

#clicking on economy button
economy=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))
time.sleep(2)


#clicking on gdp of indian states
indian_states=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")

try:
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href')) 
time.sleep(2)


#scraping rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    rank.append('No details available')
time.sleep(2)


#scraping States
State=[]
try:
    states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        State.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    State.append('No details available')
time.sleep(2)


#scraping GSDP(19-20)
GSDP_20=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in info:
        GSDP_20.append(i.text)
except NoSuchElementException:           #handling no such element exception
    GSDP_20.append('No details available')
time.sleep(2)    
    
#scraping GSDP(18-19)
GSDP_19=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in info:
        GSDP_19.append(i.text)
except NoSuchElementException:        #handling no such element exception
    GSDP_19.append('No details available')
time.sleep(2)

#scraping share (18-19)
share=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in info:
        share.append(i.text)
except NoSuchElementException:          #handling no such element exception
    share.append('No details available')
time.sleep(2)

#scraping GDP(billion$)
GDP_billion=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in info:
        GDP_billion.append(i.text)
except NoSuchElementException:            #handling no such element exception
    GDP_billion.append('No details available')
time.sleep(2)

#creatng dataframe
df=pd.DataFrame({'Rank':rank,
                'State':State,
                'GSDP(19-20)':GSDP_20,
                'GSDP(18-19)':GSDP_19,
                'Share(18-19)':share,
                'GDP(Billion_$)':GDP_billion})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

Q5. Scrape the details of trending repositories on Github.com. Url = https://github.com/ You have to find the following details: A) Repository title B) Repository description C) Contributors count D) Language used Note: - From the home page you have to click on the trending option from Explore menu through code.

In [43]:
url = "https://github.com/trending"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe") 
driver.get(url)
driver.maximize_window()

Legality Response number from our URL is: <Response [200]>

In [44]:
# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2) 

    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
    #scraping repositories discription
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,DrKLO / Telegram,Telegram for Android source,16,"[Java, C++, C, Assembly, Perl, Go]"
1,commaai / openpilot,openpilot is an open source driver assistance ...,254,"[Python, C++, C, MATLAB, Perl, Shell]"
2,flutter / flutter,Flutter makes it easy and fast to build beauti...,933,"[Dart, Objective-C, Java, C++, Shell, Ruby]"
3,pi-hole / pi-hole,A black hole for Internet advertisements,196,"[Shell, Python, Roff, PHP, CSS, Dockerfile]"
4,coolsnowwolf / lede,Lean's OpenWrt source,272,"[C, Makefile, Shell, Roff, Lua, Python]"
5,Python-World / python-mini-projects,A collection of simple python mini projects to...,93,"[Python, HTML]"
6,babysor / MockingBird,🚀AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 s...,13,"[JavaScript, Python, HTML]"
7,bevyengine / bevy,A refreshingly simple data-driven game engine ...,283,"[Rust, GLSL, Shell]"
8,AsyncBanana / microdiff,"A fast, zero dependency object and array compa...",No details available,"[JavaScript, TypeScript]"
9,smartcontractkit / full-blockchain-solidity-co...,"Ultimate Solidity, Blockchain, and Smart Contr...",4,[No languages used]
10,ixartz / Next-js-Boilerplate,"🚀 Boilerplate and Starter for Next.js 12+, Tai...",3,"[TypeScript, JavaScript, CSS, Shell]"
11,bitcoin / bitcoin,Bitcoin Core integration/staging tree,828,"[C++, Python, C, M4, Shell, Makefile]"
12,coofcookie / Windows11Upgrade,Windows 11 Upgrade tool that bypasses Microsof...,No details available,[C#]
13,TheAlgorithms / Python,All Algorithms implemented in Python,786,[Python]
14,Kholid060 / automa,A chrome extension for automating your browser...,4,"[Vue, JavaScript, CSS, HTML]"
15,3b1b / manim,Animation engine for explanatory math videos,134,"[Python, GLSL, TeX]"
16,freefq / free,翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ray/trojan节点、蓝...,2,[No languages used]
17,vxunderground / MalwareSourceCode,Collection of malware source code for a variet...,4,"[Assembly, C, Brainfuck, Roff, Limbo, E]"
18,raysan5 / raylib,A simple and easy-to-use library to enjoy vide...,279,"[C, Makefile, CMake, Shell, HTML, Batchfile]"
19,bregman-arie / devops-exercises,"Linux, Jenkins, AWS, SRE, Prometheus, Docker, ...",64,"[Python, HTML, Groovy, Shell]"
20,v2fly / v2ray-core,A platform for building proxies to bypass netw...,111,[Go]
21,obsproject / obs-studio,OBS Studio - Free and open source software for...,461,"[C, C++, CMake, Objective-C++, Objective-C, Sh..."
22,solana-labs / solana,"Web-Scale Blockchain for fast, secure, scalabl...",223,"[Rust, TypeScript, Shell, SCSS, C, Python]"
23,questdb / questdb,An open source SQL database designed to proces...,50,"[Java, C++, C, Assembly, TypeScript, JavaScript]"
24,CSSEGISandData / COVID-19,"Novel Coronavirus (COVID-19) Cases, provided b...",8,[No languages used]


Q6. Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/ You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [25]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe")
time.sleep(2)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)


#clicking the hot 100 songs link
charts=driver.find_element_by_xpath("//ul[@class='header__subnav__list display--flex flex--left-center flex-md--center-center']//li[3]//a")
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)


#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)    


#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('No details available')
time.sleep(2)
    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(2)

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(2)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,Certified Lover Boy,Drake,2,1,8
1,Dangerous: The Double Album,Morgan Wallen,8,1,42
2,Planet Her,Doja Cat,7,2,18
3,"Sincerely, Kentrell",YoungBoy Never Broke Again,6,1,5
4,Sour,Olivia Rodrigo,9,1,23
...,...,...,...,...,...
195,High Off Life,Future,197,1,76
196,My Beautiful Dark Twisted Fantasy,Kanye West,199,1,157
197,To Hell With It,PinkPantheress,73,73,2
198,Cry Baby,Melanie Martinez,-,6,136
199,Born Sinner,J. Cole,191,1,117

Q7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/ You have to find the following details: A) Name B) Designation C) Company D) Skills they hire for E) Location Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [26]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe") 
time.sleep(2)

# Opening the naukri.com
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)

#clicking on recruiters link
recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

#scrapping names
name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:           #handling no such element exception
    name.append('No details available')
time.sleep(2)


#scrapping designation
designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:        #handling no such element exception
    designation.append('No details available')
time.sleep(2)


#scrapping company names
company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:#handling no such element exception
    company.append('No details available')
time.sleep(2)

#scrapping location names
location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

#skills they hire for
skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:        #handling no such element exception
    skill.append('No details available')
time.sleep(2)    
        
#creating dataframe
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills I hire':skill})
df

,Name,Designation,Company,Location,Skills I hire
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Narasimha,Company Recruiter,Step Next Private Limited,Hyderabad / Secunderabad,"Data Modeling, Data Wrangling, seaborn, eda, p..."
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
9,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
12,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
19,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
31,Radha Manivasagam,HR Executive,Techcovery,Bengaluru / Bangalore,"Python, Artificial Intelligence, Machine Learn..."
32,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
34,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
35,Prateek Kumar,Head,Trisect,Noida,"Java, Python, Angularjs, Software Testing, Mac..."
36,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
37,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
42,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
45,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
47,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
48,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
49,Amir Chowdhury,Managing Partner,Granular.ai,No details available,"Machine Learning, Data Science, Product Manage..."

Q8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/ You have to find the following details: A) Book name B) Author name C) Volumes sold D) Publisher E) Genre

In [27]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe")
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

#scrapping book names
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scrapping author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)    

#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scrapping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details: A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

In [28]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe")
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)


# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
time.sleep(2)


# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)


# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
time.sleep(2)


# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
time.sleep(2)

# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,895,644"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"926,921"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"910,646"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"272,499"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"232,918"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,303"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,123"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"179,393"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"37,578"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"211,140"

Q10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ You have to find the following details: A) Dataset name B) Data type C) Task D) Attribute type E) No of instances F) No of attribute G) Year Note: - from the home page you have to go to the ShowAllDataset page through code

In [29]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Users\Gupta's\Downloads\chromedriver_win32/chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021